[package]
name = "bytecode"
version = "0.1.0"
edition = "2024"

[dependencies]
parser = { path = "../../parser" }
lexer = { path = "../../lexer" }
typecheck = { path = "../../typecheck" }
ast = { path = "../../ast" }
